prot_api.config(function($routeProvider,$translateProvider,$locationProvider){
	$routeProvider.when("/", {
		templateUrl : "templates/index.html",
		
		
	}).when("/error", {
		templateUrl : "templates/listE.html",
		controller : "errorController"
	}).when("/lista", {
		templateUrl : "templates/listA.html",
		controller : "appController"		
	}).when("/login", {
		templateUrl : "templates/login.html",
	}).when("/version", {
		templateUrl : "templates/version.html",
	}).when("/meters", {
		templateUrl : "templates/meters.html",
	}).when("/meters_less", {
		templateUrl : "templates/meters_less.html",
	}).when("/meters_search", {
		templateUrl : "templates/meters_search.html",
	}).when("/meters_search_less", {
		templateUrl : "templates/meters_search_less.html",
	}).when("/meters_", {
		templateUrl : "templates/meters_.html",
	}).when("/meters_b", {
		templateUrl : "templates/meters_b_less.html",
	}).when("/meters_2", {
		templateUrl : "templates/meters_2.html",
	}).when("/meters_b_1", {
		templateUrl : "templates/meters_b_1.html",
	}).when("/meters_b_2", {
		templateUrl : "templates/meters_b_2.html",
	}).when("/meters_state_relay", {
		templateUrl : "templates/meters_state_relay.html",
	}).when("/meters_reset_meter", {
		templateUrl : "templates/meters_reset_meter.html",
	}).when("/alarms_startDate_endDate", {
		templateUrl : "templates/alarms_startDate_endDate.html",
	}).when("/alarms_num_serie", {
		templateUrl : "templates/alarms_num_serie.html",
	}).when("/alarms_SD_ED_NS", {
		templateUrl : "templates/alarms_SD_ED_NS.html",
	}).when("/alarms_SD_ED_Limit", {
		templateUrl : "templates/alarms_SD_ED_Limit.html",
	}).when("/alarms_SD_ED_LT_READ", {
		templateUrl : "templates/alarms_SD_ED_LT_READ.html",
	}).when("/system", {
		templateUrl : "templates/system.html",
	}).when("/system_less", {
		templateUrl : "templates/system_less.html",
	}).when("/system_I", {
		templateUrl : "templates/system_I.html",
	}).when("/HM_IM_SD_ED", {
		templateUrl : "templates/HM_IM_SD_ED.html",
	}).when("/HM_IM_SD_ED_TYPE", {
		templateUrl : "templates/HM_IM_SD_ED_TYPE.html",
	}).when("/IR_MI_SD_ED", {
		templateUrl : "templates/IR_MI_SD_ED.html",
	}).when("/statistics", {
		templateUrl : "templates/statistics.html",
	}).when("/m_reading", {
		templateUrl : "templates/m_reading.html",
	}).when("/m_sync", {
		templateUrl : "templates/m_sync.html",
	}).when("/displays", {
		templateUrl : "templates/displays.html",
	}).when("/displays_I", {
		templateUrl : "templates/displays_I.html",
	}).when("/displaysMeters", {
		templateUrl : "templates/displaysMeters.html",
	}).when("/displaysMeters_I", {
		templateUrl : "templates/displaysMeters_I.html",
	}).when("/displays_B", {
		templateUrl : "templates/displays_B.html",
	}).when("/U_firmware", {
		templateUrl : "templates/U_firmware.html",
	}).when("/M_Config", {
		templateUrl : "templates/M_Config.html",
	}).when("/M_A00003_C", {
		templateUrl : "templates/M_A00003_C.html",
	}).when("/m_config_I", {
		templateUrl : "templates/m_config_I.html",
	}).when("/M_TP", {
		templateUrl : "templates/M_TP.html",

	}).when("/commands", {
		templateUrl : "templates/commands_.html",
	}).when("/meters_fw", {
		templateUrl : "templates/meters_fw.html",
	}).when("/meters_SN_OP", {
		templateUrl : "templates/meters_sn_op.html",

	}).when("/unsolicited_requests", {
		templateUrl : "templates/unsolicited_requests.html"

	})
	
	
	//este es digamos, al igual que en un switch el default, en caso que 
	//no hayamos concretado que nos redirija a la página principal
	.otherwise({ reditrectTo : "/" });


 

	 $translateProvider.translations('en', {
	 	//PANEL IZQUIERDO
	 	'SEARCH' : 'Search :',
	 	'PANEL_HOME'  : 'HOME', 
	 	'PANEL_LISER' : 'List of Error', 
	 	'PANEL_LISAP' : 'List of API available',
	 	'PANEL_LOGIN' : 'Login',
	 	'PANEL_VERSI' : 'Version',
	 	'PANEL_METER' : 'Meters',
	 	'PANEL_PMETE' : 'Parameters',
	 	'PANEL_NONEN' : 'NONE',
	 	'PANEL_RESJS' : 'JSON Response',
	 	'PANEL_MEANI' : 'MEANING',
	 	'PANEL_TYPER' : 'TYPE',
	 	'PANEL_VALUE' : 'VALUES',
	 	'PANEL_VERAP' : 'Version of API',
	 	'PANEL_VERFW' : 'Version of framework',
	 	'PANEL_TIMLI' : 'Time on line',
	 	'PANEL_ENGIN' : 'Integrated Development Environment',
	 	'PANEL_BUILD' : 'Build date of framework',
	 	'PANEL_MODUL' : 'Type of modules',
	 	'PANEL_VERSS' : 'Version of type modules',
	 	// Apartado Principal
	 	'TITLE_ONE' : 'REST APIs',
		'PARAG_ONE' : 'The REST APIs provide programmatic access to read and write Protcloud data. Add new smart meter, delete a smart meter, update a smart meter information, read and write system information, and more. The REST API identifies Protcloud applications and users using JWE; responses are available in JSON.',
		'TITLE_TWO' : 'Authentication JWE',
		'PARAG_TWO' : 'JWE represents encrypted content using JSON data structures and base64url encoding. The representation consists of three parts: the JWE Header, the JWE Encrypted Key, and the JWE Ciphertext. The three parts are base64url-encoded for transmission, and typically represented as the concatenation of the encoded strings in that order, with the three strings being separated by period (.) characters.',
		'PARAG_THR' : 'JWE utilizes encryption to ensure the confidentiality of the contents of the Plaintext. JWE does not add a content integrity check if not provided by the underlying encryption algorithm. If such a check is needed, an algorithm providing it such as AES-GCM [NIST 800 38D] can be used, or alternatively, it can be provided through composition by encrypting a representation of the signed content (Jones Michael B., 2011).',
		'PARAG_FOU' : 'Thanks to the advantages of JWE, PROTCLOUD used JWE-based authentication, which allows interoperability and scalability to new technological needs.',
		'PARAG_FIV' : 'To obtain a JWT, its necessary login on PROTCLOUD with an app ID and password.',
		'PARAG_SIX' : 'This can be obtained by registering on the following link https://protcloud.com/app/v1/Register',
		'PARAG_SEV' : 'After registration of the application, we obtain the following information:',
		'PARAG_EIG' : 'name_app: "name_of_app"',
		'PARAG_NIN' : 'secret_key: "new_secret"',
		'PARAG_TEN' : 'It will be used to obtain a JWE through a login.',

		//list of error
		'LOE_TITTLE':'LIST OF API ERRORS',
		'LOE_ERROR':'ERROR',
		'LOE_MEANING':'MEANING',
		//LIST OF API AVIABLE
		'LOAA_TITTLE':'LIST OF API AVIABLE',
		'LOAA_METHOD':'METHOD',
		'LOAA_ACTION':'ACTION',


		//TITLE_LOGIN : 'Login or Create an Account'

		//Apartado Login
		'LOGIN_TITLE' : 'Login to the API',
		'LOGIN_SAUTH' : 'About application-only auth',
		'LOGIN_SUBTO' : 'Tokens are passwords',
		'LOGIN_PARAG' : 'Keep in mind that the consumer key & secret, bearer token credentials, and the bearer token itself grant access to make requests on behalf of an application. These values should be considered as sensitive as passwords and must not be shared or distributed to untrusted parties.',
		'LOGIN_RESSL' : 'SSL absolutely required',
		'LOGIN_USESS' : 'This manner of authentication is only secure if SSL is used. Therefore, all requests (both to obtain and use the tokens) must use HTTPS endpoints, which is also a requirement of using API v1. Please follow the best practices detailed in Connecting to Protcloud API using SSL - peers should always be verified.',
		'LOGIN_TAPPL' : 'Issuing application-only requests',
		'LOGIN_SOLAP' : 'First of all, it necessary to encode the secret key with SHA-128 then use it as credentials to obtain a bearer token.',
		'LOGIN_FIELD' : 'FIELD',
		'LOGIN_VALUE' : 'VALUE',
		'LOGIN_OBTOK' : 'Obtain a bearer tokens',
		'LOGIN_CASHA' : 'Once you calculated the SHA-1 of the secret key, you will use it in a new request.',
		'LOGIN_HTTPP' : 'The request must be a HTTP POST request.',
		'LOGIN_NAMEA' : 'The request must be include name_app and secret key',
		'LOGIN_REURL' : 'Resource URL',
		'LOGIN_RESIN' : 'Resource information',
		'LOGIN_METHO' : 'METHOD',
		'LOGIN_REFOR' : 'RESPONSE FORMATS',
		'LOGIN_DEDAT' : 'DECRYPTED DATA',
		'LOGIN_REQAU' : 'REQUIRES AUTHENTICATION?',
		'LOGIN_TYPRE' : 'TYPE REQUEST',
		'LOGIN_CODAT' : 'CONTENT DATA',
		'LOGIN_ENCRY' : 'ENCRYPTED (OPTIONAL)',
		'LOGIN_ALGOR' : 'ALGORITHM (OPTIONAL)',
		//Apartado Version
		'VERSI_TITLE' : 'Version to the API',
			
		//Meters
			'TITLE_UNO' : 'RESOURCE URL' ,
			'METERS_UNO' : 'RESOURCE INFORMATION' ,
			'METERS_DOS' : 'METHOD' ,
			'METERS_TRES' : 'RESPONSE FORMATS' ,
			'METERS_CUATRO' : 'DECRYPTED DATA' ,
			'METERS_CINCO' : 'REQUIRES AUTHENTICATION?' ,
			'METERS_SEIS' : 'YES' ,
			'METERS_SIETE' : 'TYPE REQUEST' ,
			'METERS_OCHO' : 'REQUEST' ,
			'METERS_NUEVE' : 'RESPONSE' ,
			'METERS_DIEZ' : 'EXAMPLE IN POSTMAN:' ,
			'METERS_ONCE' : 'There are multiple results from an array with all smart meters to a false result with the error description.' ,
			'METERS_DOCE' : 'It indicates that any smart meter was found:' ,
			'METERS_TRECE' : 'FIELD' ,
			'METERS_CATORCE' : 'MEANING' ,
			'METERS_QUINCE' : 'TYPE' ,
			'METERS_DIECISEIS' : 'VALUES' ,
			'METERS_DIECISIETE' : 'Error in transaction' ,
			'METERS_DIECIOCHO' : 'Unique error detect' ,
			'METERS_DIECINUEVE' : 'Description of error' ,		
			'METERS_II' : 'Or an Array with data Smart meters:' ,
			'METERS_II_UNO' : 'INFO_METER' ,
			'METERS_II_DOS' : 'INFO_METER is applicable for all types of smart meters' ,
			'METERS_II_TRES' : 'Unique ID' ,
			'METERS_II_CUATRO' : 'Meter position in the cabinet' ,
			'METERS_II_CINCO' : 'Meter position in the cabinet type of smart meter' ,
			'METERS_II_SEIS' : 'Serial number of the smart meter' ,
			'METERS_II_SIETE' : 'Meter code given by cfe' ,
			'METERS_II_OCHO' : 'Lot number manufacturer' ,
			'METERS_II_NUEVE' : 'Date of smart meter' ,
			'METERS_III' : 'MAC address of the smart meter' ,
			'METERS_III_UNO' : 'Timestamp of data' ,
			'METERS_III_DOS' : 'Quality communications' ,
			'METERS_III_TRES' : 'Meter status' ,
			'METERS_III_CUATRO' : 'SICOM status' ,
			'METERS_III_CINCO' : 'Address bus' ,
			'METERS_III_SEIS' : 'Latitude ' ,
			'METERS_III_SIETE' : 'Longitude' ,
			'METERS_III_OCHO' : 'Time polling of smart meter' ,
			'METERS_III_NUEVE' : 'STATUS_METER' ,
			'METERS_IV' : 'STATUS_METER is applicable for all types of smart meters',
			'METERS_IV_UNO' : 'Indicates the status of the RTC (real time clock)',
			'METERS_IV_DOS' : 'Indicates the status of the flash memory ',
			'METERS_IV_TRES' : 'Indicates the status of the memory eeprom',
			'METERS_IV_CUATRO' : 'Indicates the status of mesure voltaje',
			'METERS_IV_CINCO' : 'Indicates position of Smart meter',
			'METERS_IV_SEIS' : 'Indicates state of relay',
			'METERS_IV_SIETE' : 'CONSUMPTION_PHASES',
			'METERS_IV_OCHO' : 'This section contains all consumption of the phases, identifying each of the phase in a different section.',
			'METERS_IV_NUEVE' : 'Sections availables:',
			'METERS_V' : 'PHASE_I',
			'METERS_V_UNO' : 'PHASE_II',
			'METERS_V_DOS' : 'PHASE_III',
			'METERS_V_TRES' : 'Total kWh delivered to the customer',
			'METERS_V_CUATRO' : 'Total CFE KWh delivered by the customer.',
			'METERS_V_CINCO' : 'The total balance of kWh delivered and received',
			'METERS_V_SEIS' : 'Total KVArh of the first quadrant',
			'METERS_V_SIETE' : 'Total KVArh of the second quadrant',
			'METERS_V_OCHO' : 'Total KVArh of the third quadrant',
			'METERS_V_NUEVE' : 'Total KVArh of the fourth quadrant',
			'METERS_VI' : 'INSTANTANEOUS_PHASES',
			'METERS_VI_I' : 'This section contains all instantaneous values of the phases, identifying each of the phase in a different section.',
			'METERS_VI_UNO' : 'Last voltage recorded ',
			'METERS_VI_DOS' : 'Last current recorded',
			'METERS_VI_TRES' : 'Last power factor recorded',
			'METERS_VI_CUATRO' : 'Last apparent power recorded ',
			'METERS_VI_CINCO' : 'Last active power recorded ',
			'METERS_VI_SEIS' : 'Last reactive power recorded ',
			'METERS_VI_SIETE' : 'Last frequency recorded ',
			'METERS_VI_OCHO' : 'PEAK_DEMAND_PHASES',
			'METERS_VI_NUEVE' : 'This section contains the demand maxim of the phases, identifying each of the phase in a different section.',
			'METERS_VII' : 'Total demand in phase',
			//api/v1/meters/less
			'LESS_' : 'PARAMETERS',
			'LESS' : 'NONE',
			'LESS_I' : 'Serial number of the smart meter',
			'LESS_II' : 'Timestamp of data',
			'LESS_III' : 'Meter status',
			'LESS_IV' : 'Indicates state of relay',
			'LESS_V' : 'Indicates the status of mesure voltaje',
			'LESS_VI' : 'Maxim demand in phase',
			
			//meters/search/?
			'METERSEARCH_I' : 'PARAMETERS URL',
			'METERSEARCH_II' : 'UNIQUE ID METER',
			'METERSEARCH_III' : 'INTEGER',
			'METERSEARCH_IV' : 'OR',
			'METERSEARCH_V' : 'SERIAL NUMBER',
			'METERSEARCH_VI' : 'STRING',
			
			//meters/search/?/less
			'LESS_S_I' : 'Serial number of smart meter',
			'LESS_S_II' : 'Timestamp of data',
			'LESS_S_III' : 'Meter status',
			'LESS_S_IV' : 'Indicates state of relay',
			'LESS_S_V' : 'Indicates the status of mesure voltaje',
			
			//meters_
			'meters_I' : 'CONTENT DATA',
			'meters_II' : 'ADDRESS',
			'meters_III' : 'MAC',
			'meters_IV' : 'SERIAL_NUMBER',
			'meters_V' : 'TYPE_PROTOCOL',
			'meters_VI' : 'TYPE_ZB_PROTOCOL',
			'meters_VII' : 'TYPE_METER',
			'meters_VIII' : 'Json Response',
			'meters_IX' : 'RESULT OF A SUCCESFUL TRANSACTION',
			'meters_X' : 'UID OF NEW SMART METER',
			'meters_XI' : 'Or an error with the description',
			//meters_b_1
			'meters_b_1_I' : 'CONTENT DATA',
			'meters_b_1_II' : 'SLOT',
			'meters_b_1_III' : 'TYPE_METER',
			'meters_b_1_IV' : 'SERIAL_NUMBER',
			'meters_b_1_V' : 'CODE_METER',
			'meters_b_1_VI' : 'MAC',
			'meters_b_1_VII' : 'ADDRESS',
			'meters_b_1_VIII' : 'LATITUDE',
			'meters_b_1_IX' : 'LONGITUDE',
			'meters_b_1_X' : 'RESULT OF A SUCCESFUL TRANSACTION',
			'meters_b_1_XI' : 'Or an error with the description',
			//meters_state_relay
			'm_s_r_I' : 'JSON response with an Array with an object for each meter',
			'm_s_r_II' : 'RESULT OF A SUCCESFUL TRANSACTION',
			'm_s_r_III' : 'UID OF NEW SMART METER',
			'm_s_r_IV' : 'TICKET OF TRANSACTION',
			'm_s_r_V' : 'UID of new smart meter',
			// meters/reset_meter
			'm_r_m_I':'Note: If applicable option 2 was restoring meter settings, decimal values will by automatic zero.',
			//alarms?startDate=?&endDate
			'ASD_I':'JSON response with an Array with an object for each alarm, there are two different type of alarm, meter alarm and system alarm:',
			'ASD_II':'An alert system has the following structure: ',
			'ASD_III':'indicates the type of alarm',
			'ASD_IV':'Unique code for identifying alert',
			'ASD_V':'Timestamp of alert with Mysql format',
			'ASD_VI':'Note: The types of alarms are: meter or DCU',
			'ASD_VII':'An alert meter has the following structure:',
			'ASD_VIII':'Indicates the type of alarm',
			'ASD_IX':'Serial number of meter',
			'ASD_X':'Unique code for identifying alert',
			'ASD_XI':'Timestamp of alert with Mysql format',
			'ASD_XII':'Consumption stamping',
			'ASD_XIII':'Note: The types of alarms are: meter or DCU',
			'ASD_XIV':'List of alerts in the system',
			'ASD_XV':'CODE ALARM',
			'ASD_XVI':'MEANING',
			'ASD_XVII':'DCU in battery mode',
			'ASD_XVIII':'DCU offline',
			'ASD_XIX':'Incorrect login',
			'ASD_XX':'Command execution attempt without Login',
			'ASD_XXI':'Attempt to create new meter without login',
			'ASD_XXII':'Meter attempt to create without permission',
			'ASD_XXIII':'Meter attempt removal without login',
			'ASD_XXIV':'Meter attempt removal without permission',
			'ASD_XXV':'Attempt to upgrade without login',
			'ASD_XXVI':'Attempt to upgrade without permission',
			'ASD_XXVII':'Failed upgrade',
			'ASD_XXVIII':'Attempt to modify the configuration of the DCU wit...',
			'ASD_XXIX':'Attempt to modify the configuration of the DCU wit...',
			'ASD_XXX':'Cabinet opening',
			'ASD_XXXI':'Unknow',
			'ASD_XXXII':'Critical comunication',
			'ASD_XXXIII':'List of alerts in the meter',
			'ASD_XXXIV':'Reserved',
			'ASD_XXXV':'Reserved',
			'ASD_XXXVI':'Failure relay',
			'ASD_XXXVII':'Overflowed value',
			'ASD_XXXVIII':'Failure real time clock',
			'ASD_XXXIX':'Restoring real time clock',
			'ASD_XL':'Optical access port',
			'ASD_XLI':'Damaged measurement records',
			'ASD_XLII':'Reset events',
			'ASD_XLIII':'External fault memory',
			'ASD_XLIV':'Internal fault memory',
			'ASD_XLV':'Failure measurement',
			'ASD_XLVI':'Reset settings',
			'ASD_XLVII':'Re-programming MODE',
			'ASD_XLVIII':'Firmware update',
			'ASD_XLIX':'Re-programming of parameters',
			'ASD_L':'Resetting meter records',
			'ASD_LI':'Re-programming of date and time',
			'ASD_LII':'Return voltage setpoint',
			'ASD_LIII':'Disconnect exhausted balance',
			'ASD_LIV':'Disconnection of service due command',
			'ASD_LV':'Power failure',
			'ASD_LVI':'Restoring power',
			'ASD_LVII':'Demand exceeded alarm',
			'ASD_LVIII':'Retirement meter base',
			'ASD_LIX':'Meter positioned correctly',
			'ASD_LX':'Disconnection for non-payment',
			'ASD_LXI':'Credit recharge successful',
			'ASD_LXII':'Alarm High Voltage',
			'ASD_LXIII':'Alarm low voltage',
			'ASD_LXIV':'Reconnection of service user',
			'ASD_LXV':'Meter with reversed position',
			'ASD_LXVI':'Reverse energy flow',
			'ASD_LXVII':'Re-Connection by command',
			'ASD_LXVIII':'Flow correct current',
			'ASD_LXIX':'Failure by buying credit',
			'ASD_LXX':'Registration successful payment',
			'ASD_LXXI':'Failure to pay registration',
			'ASD_LXXII':'Disconnect user',
			'ASD_LXXIII':'Reconnection by buying credit',
			'ASD_LXXIV':'Return of demand at nominal value',
			'ASD_LXXV':'Test mode activated',
			'ASD_LXXVI':'Phase bridged',
			'ASD_LXXVII':'Bridged retirement phase',
			'ASD_LXXVIII':'Invalid password',
			'ASD_LXXIX':'Reconnect remote port',
			'ASD_LXXX':'Reconnect optical port',
			'ASD_LXXXI':'Schedule change',
			'ASD_LXXXII':'Buffer full events',
			'ASD_LXXXIII':'Remote shutdown port',
			'ASD_LXXXIV':'Reconnect optical port',
			//alarms_num_serie
			'ANS_I':'Note: The type alarms is of meter',
			//System
			'system_I':'UID of data concentrator unit',
			'system_II':'Id name of data concentrator unit',
			'system_III':'Timestamp of data',
			'system_IV':'Cpu usage (%)',
			'system_V':'Ram usage (%)',
			'system_VI':'Hdd usage (%)',
			'system_VII':'Total ram (Gb)',
			'system_VIII':'Total space available (Gb)',
			'system_IX':'Model of data concentrator unit',
			'system_X':'Type of architecture',
			'system_XI':'System release',
			'system_XII':'System version',
			'system_XIII':'Number of meters available',
			'system_XIV':'Number of meters not available',
			'system_XV':'Time polling',
			'system_XVI':'Time to update system',
			'system_XVII':'During  last time polling',
			'system_XVIII':'Name of firmware',
			//System/less
			'SL_I':'Availability of system',
			'SL_II':'Status of battery',
			//system_I
			'system_I_I':'Object to send:',
			'system_I_II':'Note: SSL_ACTIVE_MQTT, in this version is not available.',
			'system_I_III':'Unique API of concentrator (optional)',
			'system_I_IV':'Frequency request to meters [5,10,15,30,60,1440] in minutes (optional)',
			'system_I_V':'Frequency request of the system info (optional)',
			'system_I_VI':'Parameter to enable or disable the microswitch (optional)',
			'system_I_VII':'Update date',
			'system_I_VIII':'IP ver. 4 of concentrator (optional)',
			'system_I_IX':'Netmask ver.4 of concentrator (optional)',
			'system_I_X':'Gateway ver.4 of concentrator (optional)',
			'system_I_XI':'IP of MQTT server (optional)',
			'system_I_XII':'Enable SSL mode (optional)',
			'system_I_XIII':'IP OF MQTT server (optional)',
			'system_I_XIV':'Enable SSL mode (optional)',
			'system_I_XV':'User of MQTT (optional)',
			'system_I_XVI':'Password of MQTT',
			'system_I_XVII':'Topic where alarms will be sent (optional)',
			'system_I_XVIII':'Latitude of concentrator (optional)',
			'system_I_XIX':'Longitude of concentrator (optional)',
			'system_I_XX':'Result of a successful transaction',
			'system_I_XXI':'Or',
			'system_I_XXII':'Result of a transaction failed',
			'system_I_XXIII':'Error code for detect the problem',
			'system_I_XXIV':'Note: CODE_ERROR (PENDING LIST)',
			//history_meter/id_meter/starDate/endDate
			'HM_IM_SD_ED_I':'Note: The record of load profile is displayed per day and every 15 minutes ',
			'HM_IM_SD_ED_II':'LOAD_PROFILE',
			'HM_IM_SD_ED_III':'Array with daily load profiles',
			'HM_IM_SD_ED_IV':'DATE',
			'HM_IM_SD_ED_V':'Day of profile',
			'HM_IM_SD_ED_VI':'TIME',
			'HM_IM_SD_ED_VII':'Hour',
			'HM_IM_SD_ED_VIII':'TYPE',
			'HM_IM_SD_ED_IX':'CHANNEL',
			'HM_IM_SD_ED_X':'Channel of communication',
			'HM_IM_SD_ED_XI':'VALUES',
			'HM_IM_SD_ED_XII':'ALERTS',
			'HM_IM_SD_ED_XIII':'List of events occurred in the selected dates',
			'HM_IM_SD_ED_XIV':'Note: The communication channel receives the following parameters:',
			'HM_IM_SD_ED_XV':'Energy delivered (kWh)',
			'HM_IM_SD_ED_XVI':'Energy received (kWh)',
			'HM_IM_SD_ED_XVII':'Quadrante I (kVAR)',
			'HM_IM_SD_ED_XVIII':'Quadrante II (kVAR)',
			'HM_IM_SD_ED_XIX':'Quadrante III (kVAR)',
			'HM_IM_SD_ED_XX':'Quadrante IV (kVAR)',
			'HM_IM_SD_ED_XXI':'Demand delivered (kW)',
			'HM_IM_SD_ED_XXII':'Demand received (kW)',
			//history_meter/id_meter/starDate/endDate/tipe
			'HM_IM_SD_ED_T_I':'Note:  If the channel type is not specified in the URL of the request channel data I show default.',
			'HM_IM_SD_ED_T_II':'Note: If the result is negative (“value”:-1) means no profile.',
			///instant_record/meder_id/starDate/endDate
			'IR_MI_SD_ED_I':'Note: Instant saved every 15 minutes',
			'IR_MI_SD_ED_II':'Timestamp of instant',
			'IR_MI_SD_ED_III':'Current',
			'IR_MI_SD_ED_IV':'Voltage',
			'IR_MI_SD_ED_V':'Active power',
			'IR_MI_SD_ED_VI':'Active power',
			'IR_MI_SD_ED_VII':'Aparent power',
			'IR_MI_SD_ED_VIII':'Ractive power',
			'IR_MI_SD_ED_IX':'Frequency power',
			'IR_MI_SD_ED_X':'Total KWH delivered',
			'IR_MI_SD_ED_XI':'Total kwh received',
			'IR_MI_SD_ED_XII':'Total consumption',
			'IR_MI_SD_ED_XIII':'KVAR I TOTAL',
			'IR_MI_SD_ED_XIV':'KVAR II TOTAL',
			'IR_MI_SD_ED_XV':'Previous demand delivered ',
			'IR_MI_SD_ED_XVI':'Previous demand received',
			//statistics
			'statistics_I':'Packet delivered',
			'statistics_II':'Packet received',
			'statistics_III':'Lost packet ',
			'statistics_IV':'Meter online',
			'statistics_V':'Meter offline',
			'statistics_VI':'Time polling',
			'statistics_VII':'Timestamp of alert with MySQL format',
			'statistics_VIII':'Quality of Service',
			'statistics_IX':'Packet lost per meter',
			//meters/reading
			'M_READING_I':'Total kWh delivered to the customer',
			'M_READING_II':'Total CFE KWh delivered by the customer.',
			'M_READING_III':'The total balance of kWh delivered and received',
			'M_READING_IV':'Total KVArh of the first quadrant',
			'M_READING_V':'Total KVArh of the second quadrant',
			'M_READING_VI':'Total KVArh of the third quadrant',
			'M_READING_VII':'Total KVArh of the fourth quadrant',
			'M_READING_VIII':'Timestamp of data',
			'M_READING_IX':'Indicates state of relay',
			'M_READING_X':'Serial number of the smart meter',
			'M_READING_XI':'Ticket ',
			//meter/sync
			'm_sync_I':'State of meter',
			'm_sync_II':'Serial number of the smart meter',
			'm_sync_IIV':'Ticket',
			'm_sync_IV':'Note: The options of the state meter are: online, offline or false',
			//Displays
			'displays':'ADDRESS',
			//Displays
			'displays_I':'RESULT OF A SUCCESFUL TRANSACTION',
			//displaysMeters
			'DMeters_I':'UNIQUE NUMBER OF ASSOCIATION SMART METER -DISPLAY',
			'DMeters_II':'ADDRESS OF DISPLAY',
			'DMeters_III':'MAC OF DISPLAY',
			'DMeters_IV':'SERIAL NUMBER OF SMART METERS ASSOCIATED TO DISPLAY',
			//displaysMeters_I
			'DMetersI_I':'NOTE: The array of meters must specify the unique serial number (length: 6) each',
			//displays_B
			
			//meters/configuracion
			'M_C_I':'Address of smart meter',
			'M_C_II':'Alarm system',
			'M_C_III':'Transmission speed',
			'M_C_IV':'Type of channel (delivered energy)',
			'M_C_V':'Type of channel(energy received)',
			'M_C_VI':'Type of channel (demand delivered)',
			'M_C_VII':'Date build',
			'M_C_VIII':'Day cut pay',
			'M_C_IX':'Day of pay',
			'M_C_X':'Decimal deploy',
			'M_C_XI':'During test mode',
			'M_C_XII':'Energy fee',
			'M_C_XIII':'Version of hardware',
			'M_C_XIV':'Status of event port',
			'M_C_XV':'Status of key',
			'M_C_XVI':'Status of tarif',
			'M_C_XVII':'Key of meter',
			'M_C_XVIII':'Quadrant',
			'M_C_XIX':'Maximum voltage',
			'M_C_XX':'Minimum voltage',
			'M_C_XXI':'Minimum outage for disc',
			'M_C_XXII':'Minimum out for alarm',
			'M_C_XXIII':'Model of collector',
			'M_C_XXIV':'Operation mode',
			'M_C_XXV':'Pulse KH',
			'M_C_XXVI':'Serial number of smart meter',
			'M_C_XXVII':'Version of software',
			'M_C_XXVIII':'Template of configurations',
			'M_C_XXIX':'Time zone ',
			'M_C_XXX':'Time delay LCD',
			'M_C_XXXI':'Time zone',
			'M_C_XXXII':'Vendor',
			//meters_config_I
			'm_config_I':'NOTE: The settings file is a template (.json) exported directly from Soft Terminal program, selecting the option configuration templates operation in the parameter programming menu.',
			'm_config_II':'JSON response with an Array with an object for each meter:',
			'm_config_III':'UID OF NEW SMART METER',
			'm_config_IV':'TICKET OF TRANSACTION',


			//COMMANDS_
			'TYP_COM_C':'Command type',
			'op_mod_ty_c':'Operation mode type',
			'reg_mode_c':'Smart meter flow',
			//METERS_SN_OPERATIONMODE
			'msnop':'Operation mode',
			'msnrm':'Register mode'

			
			
			
			

			//unsolicited_request.html *INGLÉS*
			'TITILE_UNSOLICITED' : 'Unsolicited requests',
			'PARAPHUNSOL_ONE' : 'This behavior is used to send alerts or exceptional circumstances as a mechanism which uses the MQTT protocol with QoS2 quality\u002C which is the safest way. Likewise\u002C every message is encrypted with AES 128 and with a JSON format.',
			'PARAPHUNSOL_TWO' : 'Before any transaction with MQTT\u002C you must set the IP address of MQTT server\u002C user\u002C password and topic. (See more details)',
			'PARAPHUNSOL_TRE' : 'The payload structure sent is the following:',
			'SUBTITLEUNS_TWO' : 'MQTT ALERTS',
			'ONEFIELD_UNSOLI' : 'Timestamp of instant',
			'TWOFIELD_UNSOLI' : 'Consumption of meter',
			'TREFIELD_UNSOLI' : 'IUD code to identify the alarm',
			'FOUFIELD_UNSOLI' : 'Serial meter',
			'SUBTITLEUNS_TRE' : 'END PROFILES MESSAGE',
			'PARAPHUNSOL_FOU' : 'After each message API will wait for a confirmation for each sent message. The confirmation should be encrypted and a JSON format.',
			'PARAPHUNSOL_FIV' : 'The payload structure received is the following:',
			'FIVFIELD_UNSOLI' : 'All profiles are already',
			'SIXFIELD_UNSOLI' : 'Message successfully received',
			'SEVFIELD_UNSOLI' : 'Error message reception'

	});
	$translateProvider.translations('es', {
		//PANEL IZQUIERDO
		'SEARCH' : 'Buscar :',
		'PANEL_HOME'  : 'HOME', 
		'PANEL_LISER' : 'Lista de Errores', 
		'PANEL_LISAP' : 'Lista de API disponible',
		'PANEL_LOGIN' : 'Inicio de sesión',
		'PANEL_VERSI' : 'Versión',
		'PANEL_METER' : 'Medidores',
		'PANEL_PMETE' : 'Parámetros',
		'PANEL_NONEN' : 'NINGUNO',
		'PANEL_RESJS' : 'Respuesta JSON',
		'PANEL_MEANI' : 'SIGNIFICADO',
		'PANEL_TYPER' : 'TIPO',
		'PANEL_VALUE' : 'VALORES',
		'PANEL_VERAP' : 'Versión del API',
		'PANEL_VERFW' : 'Versión de framework',
		'PANEL_TIMLI' : 'Tiempo en línea',
		'PANEL_ENGIN' : 'Entorno de desarrollo integrado',
		'PANEL_BUILD' : 'Fecha de construcción deL framework	',
		'PANEL_MODUL' : 'Tipo de módulos',
		'PANEL_VERSS' : 'Versión de los tipo de modulo',
		//
		'TITLE_ONE' : 'REST APIs',
		'PARAG_ONE' : 'Una REST API proporciona acceso mediante programación para leer y escribir datos de Protcloud. Añadir un nuevo medidor inteligente, eliminar un medidor inteligente, actualizar un medidor inteligente, leer y escribir información del sistema, y más. La REST API identifica aplicaciones Protcloud y los usuarios usan JWE; las respuestas están disponibles en JSON.',
		'TITLE_TWO' : 'Autenticación JWE',
		'PARAG_TWO' : 'JWE representa contenido cifrado usando estructuras de datos JSON y codificación base64url. La representación consta de tres partes: el encabezado JWE, la clave cifrada JWE y el texto cifrado JWE. Las tres partes están codificadas en base64url para la transmisión, y típicamente representadas como la concatenación de las cadenas codificadas en ese orden, con las tres cadenas separadas por caracteres de punto (.).',
		'PARAG_THR' : 'JWE utiliza cifrado para garantizar la confidencialidad de los contenidos del texto sin formato. JWE no añade una comprobación de integridad del contenido si no es proporcionada por el algoritmo de encriptación subyacente. Si dicha verificación es necesaria, un algoritmo que lo proporciona como AES-GCM [NIST‑800‑38D] puede usarlo, alternativamente, puede proporcionar a través de la composición mediante la encriptación de una representación del contenido firmado (Jones Michael B., 2011).',
		'PARAG_FOU' : 'Gracias a las ventajas de JWE, PROTCLOUD utiliza autenticación basada en JWE, que permite la interoperabilidad y escalabilidad a las nuevas necesidades tecnológicas.',
		'PARAG_FIV' : 'Para obtener una JWT, es necesario iniciar sesión en PROTCLOUD con un ID de aplicación y una contraseña.',
		'PARAG_SIX' : 'Esto puede obtenerse mediante el registro en el siguiente enlace',
		'PARAG_SEV' : 'Después del registro de la aplicación, obtenemos la siguiente información:',
		'PARAG_EIG' : 'name_app: "name_of_app"',
		'PARAG_NIN' : 'secret_key: "new_secret"',
		'PARAG_TEN' : 'Se utilizará para obtener un JWE a través de un inicio de sesión.',

		
		//list of error
		'LOE_TITTLE':'LISTA DE ERRORES DE API',
		'LOE_ERROR':'ERROR',
		'LOE_MEANING':'SIGNIFICADO',
		//LIST OF API AVIABLE
		'LOAA_TITTLE':'LISTA DE API DISPONIBLE ',
		'LOAA_METHOD':'MÉTODO',
		'LOAA_ACTION':'ACCIÓN',
		

		//
		'TITLE_LOGIN' : 'Iniciar Sesi\u00F3n',

		//Apartado Login 	
		'LOGIN_TITLE' : 'Acceso al API',
		'LOGIN_SAUTH' : 'Acerca de la autenticación',
		'LOGIN_SUBTO' : 'Los token son contraseñas',
		'LOGIN_PARAG' : 'Tenga en cuenta que la clave de consumidor y el secreto, las credenciales de token del portador y el token del portador en sí permiten el acceso para realizar solicitudes en nombre de una aplicación. Estos valores deben ser considerados tan sensibles como las contraseñas y no deben ser compartidos o distribuidos a las partes no confiables.',
		'LOGIN_RESSL' : 'SSL absolutamente requerido',
		'LOGIN_USESS' : 'Esta forma de autenticación sólo es segura si se utiliza SSL. Por lo tanto, todas las solicitudes (tanto para obtener como utilizar los tokens) deben utilizar terminales de HTTPS, lo que también es un requisito al utilizar API v1. Siga las prácticas recomendadas detalladas en Conexión a  la API de Protcloud usando SSL usando SSL - los pares deben ser verificados siempre.',
		'LOGIN_TAPPL' : 'Emitir las solicitudes de aplicación',
		'LOGIN_SOLAP' : 'En primer lugar, es necesario codificar la clave secreta con SHA-128 y luego usarla como credenciales para obtener un token de portador.',
		'LOGIN_FIELD' : 'CAMPO',
		'LOGIN_VALUE' : 'VALOR',
		'LOGIN_OBTOK' : 'Obtener un token de portador',
		'LOGIN_CASHA' : 'Una vez calculado el SHA-1 de la clave secreta, la utilizará en una nueva solicitud.',
		'LOGIN_HTTPP' : 'La solicitud debe ser HTTP POST.',
		'LOGIN_NAMEA' : 'La solicitud debe incluir name_app y clave secreta',
		'LOGIN_REURL' : 'Recurso URL',
		'LOGIN_RESIN' : 'Información de recursos',
		'LOGIN_METHO' : 'MÉTODO',
		'LOGIN_REFOR' : 'FORMATOS DE RESPUESTA', 
		'LOGIN_DEDAT' : 'DATOS DESCIFRADOS',
		'LOGIN_REQAU' : '¿REQUIERE AUTENTICACIÓN?',
		'LOGIN_TYPRE' : 'TIPO DE SOLICITUD',
		'LOGIN_CODAT' : 'DATOS DE CONTENIDO',
		'LOGIN_ENCRY' : 'ENCRIPTACIÓN (OPCIONAL)',
		'LOGIN_ALGOR' : 'ALGORITMO (OPCIONAL)',
		//Apartado Versión
		'VERSI_TITLE' : 'Versión de la API',
		
		//Meters
		'TITLE_UNO' : 'RECURSO de URL' ,
		'METERS_UNO' : 'INFORMACIÓN DE RECURSOS' ,
		'METERS_DOS' : 'MÉTODO' ,
		'METERS_TRES' : 'FORMATOS DE RESPUESTA' ,
		'METERS_CUATRO' : 'DATOS DESCIFRADOS' ,
		'METERS_CINCO' : 'REQUIERE AUTENTICACIÓN?' ,
		'METERS_SEIS' : 'SI' ,
		'METERS_SIETE' : 'SOLICITUD DE TIPO' ,
		'METERS_OCHO' : 'SOLICITUD' ,
		'METERS_NUEVE' : 'RESPUESTA' ,
		'METERS_DIEZ' : 'EJEMPLO EN POSTMAN:' ,
		'METERS_ONCE' : 'Hay múltiples resultados de una matriz con todos los medidores inteligentes a un resultado falso con la descripción del error.' ,
		'METERS_DOCE' : 'Indica que se encontró cualquier medidor inteligente:' ,
		'METERS_TRECE' : 'CAMPO' ,
		'METERS_CATORCE' : 'SIGNIFICADO' ,
		'METERS_QUINCE' : 'TIPO' ,
		'METERS_DIECISEIS' : 'VALORES' ,
		'METERS_DIECISIETE' : 'Error en la transacción' ,
		'METERS_DIECIOCHO' : 'Detección de error única' ,
		'METERS_DIECINUEVE' : 'Descripción del error' ,		
		'METERS_II' : 'O un Array con datos de medidores inteligente:' ,
		'METERS_II_UNO' : 'MEDIDOR DE INFORMACION' ,
		'METERS_II_DOS' : 'Medidor de informacion es aplicable para todo tipo de contadores inteligentes' ,
		'METERS_II_TRES' : 'Identificación única' ,
		'METERS_II_CUATRO' : 'Posición del medidor en el armario' ,
		'METERS_II_CINCO' : 'Posición del medidor en el gabinete tipo de medidor inteligente' ,
		'METERS_II_SEIS' : 'Número de serie del medidor inteligente' ,
		'METERS_II_SIETE' : 'Código del medidor dado por cfe' ,
		'METERS_II_OCHO' : 'Fabricante del número de lote' ,
		'METERS_II_NUEVE' : 'Fecha del medidor inteligente' ,
		'METERS_III' : 'Dirección MAC del medidor inteligente' ,
		'METERS_III_UNO' : 'Fecha y hora de los datos' ,
		'METERS_III_DOS' : 'Comunicaciones de calidad' ,
		'METERS_III_TRES' : 'Estado del medidor' ,
		'METERS_III_CUATRO' : 'Estado SICOM' ,
		'METERS_III_CINCO' : 'Dirección de BUS' ,
		'METERS_III_SEIS' : 'Latitud ' ,
		'METERS_III_SIETE' : 'Longitud' ,
		'METERS_III_OCHO' : 'Tiempo de sondeo del medidor inteligente' ,
		'METERS_III_NUEVE' : 'MEDIR DE ESTADO' ,
		'METERS_IV' : 'MEDIR DE ESTADO es aplicable para todos los tipos de contadores inteligentes',
		'METERS_IV_UNO' : 'Indica el estado del RTC (reloj de tiempo real)',
		'METERS_IV_DOS' : 'Indica el estado de la memoria flash',
		'METERS_IV_TRES' : 'Indica el estado de la memoria eeprom',
		'METERS_IV_CUATRO' : 'Indica el estado del voltaje de medicion',
		'METERS_IV_CINCO' : 'Indica la posición del medidor inteligente',
		'METERS_IV_SEIS' : 'Indica el estado del Relay',
		'METERS_IV_SIETE' : 'FASES DEL CONSUMO',
		'METERS_IV_OCHO' : 'Esta sección contiene todo el consumo de las fases, identificando cada una de las fases en una sección diferente.',
		'METERS_IV_NUEVE' : 'Secciones disponibles:',
		'METERS_V' : 'FASE_I',
		'METERS_V_UNO' : 'FASE_II',
		'METERS_V_DOS' : 'FASE_III',
		'METERS_V_TRES' : 'Total kWh entregado al cliente',
		'METERS_V_CUATRO' : 'Total CFE KWh entregado por el cliente.',
		'METERS_V_CINCO' : 'El saldo total de kWh entregado y recibido',
		'METERS_V_SEIS' : 'Total KVAr del primer cuadrante ',
		'METERS_V_SIETE' : 'Total KVArh del segundo cuadrante',
		'METERS_V_OCHO' : 'Total KVArh del tercer cuadrante',
		'METERS_V_NUEVE' : 'Total KVArh del cuarto cuadrante',
		'METERS_VI' : 'FASES INSTANTANEAS',
		'METERS_VI_I' : 'Esta sección contiene todos los valores instantáneos de las fases, identificando cada una de las fases en una sección diferente',
		'METERS_VI_UNO' : 'Última tensión registrada',
		'METERS_VI_DOS' : 'Última corriente registrada',
		'METERS_VI_TRES' : 'Última factor de potencia registrada',
		'METERS_VI_CUATRO' : 'Última potencia aparente registrada',
		'METERS_VI_CINCO' : 'Última potencia activa registrada',
		'METERS_VI_SEIS' : 'Última potencia reactiva registrada',
		'METERS_VI_SIETE' : 'Última frecuencia registrada',
		'METERS_VI_OCHO' : 'FASES DE LA DEMANDA',
		'METERS_VI_NUEVE' : 'Esta sección contiene la máxima de demanda de las fases, identificando cada una de las fases en una sección diferente',
		'METERS_VII' : 'Demanda total en fase',
		//api/v1/meters/less
		'LESS_' : 'PARÁMETROS',
		'LESS' : 'NINGUNA',
		'LESS_I' : 'Número de serie del medidor inteligente',
		'LESS_II' : 'Fecha y hora de los datos',
		'LESS_III' : 'Estado del medidor',
		'LESS_IV' : 'Indica el estado del relay',
		'LESS_V' : 'Indica el estado del voltaje de medición',
		'LESS_VI' : 'Demanda máxima en fase',
		
		//meters/search/?
		'METERSEARCH_I' : 'PARAMETROS URL',
		'METERSEARCH_II' : 'MEDIDOR DE IDENTIFICACIÓN ÚNICA',
		'METERSEARCH_III' : 'INTEGER',
		'METERSEARCH_IV' : 'O',
		'METERSEARCH_V' : 'NÚMERO DE SERIE',
		'METERSEARCH_VI' : 'STRING',
		
		//meters/search/?/less
		'LESS_S_I' : 'Número de serie del medidor inteligente',
		'LESS_S_II' : 'Fecha y hora de los datos',
		'LESS_S_III' : 'Estado del medidor',
		'LESS_S_IV' : 'Indica el estado del Relay',
		'LESS_S_V' : 'Indica el estado del voltaje de medición',
		
		//meters_
		'meters_I' : 'DATOS DE CONTENIDO',
		'meters_II' : 'DIRECCIÓN',
		'meters_III' : 'MAC',
		'meters_IV' : 'NÚMERO DE SERIE',
		'meters_V' : 'TIPO DE PROTOCOLO',
		'meters_VI' : 'TIPO ZB PROTOCOLO',
		'meters_VII' : 'TIPO DE MEDIDOR',
		'meters_VIII' : 'Respuesta de JSON',
		'meters_IX' : 'Resultado de una transacción exitosa',
		'meters_X' : 'UID de nuevo medidor inteligente',
		'meters_XI' : 'O un error con la descripción',
		//meters_b_1
		'meters_b_1_I' : 'Datos del contenido',
		'meters_b_1_II' : 'Espacio',
		'meters_b_1_III' : 'Medidor de Tipo',
		'meters_b_1_IV' : 'Número de Serie',
		'meters_b_1_V' : 'Codigo de medidor',
		'meters_b_1_VI' : 'MAC',
		'meters_b_1_VII' : 'Dirección',
		'meters_b_1_VIII' : 'Latitud',
		'meters_b_1_IX' : 'Longitud',
		'meters_b_1_X' : 'RESULTADO DE UNA TRANSACCIÓN EXITOSA',
		'meters_b_1_XI' : 'O un error con la descripción',
		//meters_state_relay
		'm_s_r_I' : 'JSON respuesta con un Array con un objeto para cada Medidor',
		'm_s_r_II' : 'Resultado de una transacción exitosa',
		'm_s_r_III' : 'UID de nuevo medidor inteligente',
		'm_s_r_IV' : 'Boleto de Transacción',
		'm_s_r_V' : 'UID de nuevo medidor inteligente',
		// meters/reset_meter
		'm_r_m_I':'Nota: Si procede, la opción 2 restauraba la configuración del medidor, los valores decimales se harían por cero automático',
		//alarms?startDate=?&endDate
		'ASD_I':'JSON respuesta con un Array con un objeto para cada alarma, hay dos tipos diferentes de alarma, alarma del medidor y alarma del sistema',
		'ASD_II':'Un sistema de alerta tiene la siguiente estructura:',
		'ASD_III':'Indica el tipo de alarma',
		'ASD_IV':'Código único para identificar la alerta',
		'ASD_V':'Timestamp de alerta con formato Mysql',
		'ASD_VI':'Nota: los tipos de alarmas son: Medidor o DCU',
		'ASD_VII':'Un medidor de alerta tiene la siguiente estructura',
		'ASD_VIII':'Indica el tipo de alarma',
		'ASD_IX':'Número de serie del medidor',
		'ASD_X':'Código único para identificar la alerta',
		'ASD_XI':'Timestamp de alerta con formato Mysql',
		'ASD_XII':'Estampado de consumo',
		'ASD_XIII':'Nota: los tipos de alarmas son: Medidor o DCU',
		'ASD_XIV':'Lista de alertas en el sistema',
		'ASD_XV':'Alarma de código',
		'ASD_XVI':'Significado',
		'ASD_XVII':'DCU en modo de bateria',
		'ASD_XVIII':'DCU sin conexión',
		'ASD_XIX':'Login incorrecto',
		'ASD_XX':'Intento de ejecución de comandos sin iniciar sesión',
		'ASD_XXI':'Intento de crear un nuevo medidor sin iniciar conexión ',
		'ASD_XXII':'Medidor intente crear sin permiso',
		'ASD_XXIII':'Eliminación del intento del medidor sin iniciar sesión',
		'ASD_XXIV':'Intento de eliminación del medidor sin permiso',
		'ASD_XXV':'Intentar actualizar sin iniciar sesión',
		'ASD_XXVI':'Intento de actualización sin permiso',
		'ASD_XXVII':'Error de actualización',
		'ASD_XXVIII':'Intenta modificar la configuracion de la DCU con...',
		'ASD_XXIX':'Intenta modificar la configuracion de la DCU con...',
		'ASD_XXX':'Apertura del gabinete',
		'ASD_XXXI':'Desconocido',
		'ASD_XXXII':'Comunicación crítica',
		'ASD_XXXIII':'Lista de alertas en el Medidor',
		'ASD_XXXIV':'Reservado',
		'ASD_XXXV':'Reservado',
		'ASD_XXXVI':'Fallo de Relay',
		'ASD_XXXVII':'Valor desbordado',
		'ASD_XXXVIII':'Error en el tiempo real',
		'ASD_XXXIX':'Restauración del reloj en tiempo real',
		'ASD_XL':'Puerto de acceso optico',
		'ASD_XLI':'Registros de medición dañados',
		'ASD_XLII':'Restablecer eventos',
		'ASD_XLIII':'Memoria de fallos externos',
		'ASD_XLIV':'Memoria de fallos internos',
		'ASD_XLV':'Medición de fallos',
		'ASD_XLVI':'Reiniciar ajustes',
		'ASD_XLVII':'Reprogramación de modalidad',
		'ASD_XLVIII':'Actializacion de Firmware',
		'ASD_XLIX':'Reprogramación de parámetros',
		'ASD_L':'Restablecimiento de registros de medidores',
		'ASD_LI':'Reprogramacion de fecha y hora',
		'ASD_LII':'Consigna de voltage de retorno',
		'ASD_LIII':'Desconectar el equilibrio agotado',
		'ASD_LIV':'Desconexión del servicio debido comando',
		'ASD_LV':'Fallo de alimentacion',
		'ASD_LVI':'Restauración de la energía',
		'ASD_LVII':'Demanda superada alarma',
		'ASD_LVIII':'Base del medidor de jubilación',
		'ASD_LIX':'Medidor colocado correctamente',
		'ASD_LX':'Desconexión por falta de pago',
		'ASD_LXI':'Recargs de credito exitosa',
		'ASD_LXII':'Alarma de alto voltaje',
		'ASD_LXIII':'Alarma de baja tensión',
		'ASD_LXIV':'Reconexión del usuario del servicio',
		'ASD_LXV':'Medidor con posición invertida',
		'ASD_LXVI':'Flujo inverso de energía',
		'ASD_LXVII':'Reconexión por comando',
		'ASD_LXVIII':'Corriente correcta de flujo',
		'ASD_LXIX':'Error al comprar codigo',
		'ASD_LXX':'Registro de pago exitoso',
		'ASD_LXXI':'Falta de pago del registro',
		'ASD_LXXII':'Desconectar usuario',
		'ASD_LXXIII':'Reconexión mediante la compra de crédito',
		'ASD_LXXIV':'Retorno de la demanda al valor nominal',
		'ASD_LXXV':'Modo de prueba activo',
		'ASD_LXXVI':'Fase puenteada',
		'ASD_LXXVII':'Etapa de retiro en puente',
		'ASD_LXXVIII':'Contraseña invalida',
		'ASD_LXXIX':'Reconectar el puerto remoto',
		'ASD_LXXX':'Vuelva a conectar el puerto óptico',
		'ASD_LXXXI':'Cambio de horario',
		'ASD_LXXXII':'Regulador de eventos completos',
		'ASD_LXXXIII':'Puerto de apagado remoto',
		'ASD_LXXXIV':'Vuelva a conectar el puerto óptico',
		//alarms_num_serie
		'ANS_I':'Nota: El tipo de alarmas es de medidor',
		//System
		'system_I':'UID del concentrador de datos',
		'system_II':'Nombre de identificación de la unidad concentradora de datos',
		'system_III':'Fecha y hora de los datos',
		'system_IV':'Uso de CPU (%)',
		'system_V':'Uso de RAM (%)',
		'system_VI':'Uso de HDD (%)',
		'system_VII':'Total ram (Gb)',
		'system_VIII':'Total de espacio disponible(Gb)',
		'system_IX':'Modelo de concentrador de datos',
		'system_X':'Tipo de arquitectura',
		'system_XI':'Liberación del sistema',
		'system_XII':'Versión del sistema',
		'system_XIII':'Número de metros disponibles',
		'system_XIV':'Número de metros no disponibles',
		'system_XV':'Tiempo de votación',
		'system_XVI':'Tiempo para actualizar el sistema',
		'system_XVII':'Durante el último sondeo',
		'system_XVIII':'Nombre del firmware',
		//System/less
		'SL_I':'Disponibilidad del sistema',
		'SL_II':'Estado de la batería',
		//system_I
		'system_I_I':'Onjeto a enviar:',
		'system_I_II':'Nota: SSL_ACTIVE_MQTT, en esta versión no está disponible.',
		'system_I_III':'API única de concentrador (opcional)',
		'system_I_IV':'Solicitud de frecuencia a medidores [5,10,15,30,60,1440] en minutos (opcional)',
		'system_I_V':'Solicitud de frecuencia de la informacion del sistema (opcional)',
		'system_I_VI':'Parámetro para activar o desactivar el microinterruptor (opcional)',
		'system_I_VII':'Fecha de actualizacion',
		'system_I_VIII':'IP ver. 4 del concentrador (opcional)',
		'system_I_IX':'Netmask ver.4 del concentrador  (opcional)',
		'system_I_X':'Gateway ver.4 del concentrador  (opcional)',
		'system_I_XI':'IP de MQTT servidor (opcional)',
		'system_I_XII':'Habilitar el modo SSL (opcional)',
		'system_I_XIII':'IP del MQTT servidor (opcional)',
		'system_I_XIV':'Habilitar el modo SSL (opcional)',
		'system_I_XV':'Usuario de MQTT (opcional)',
		'system_I_XVI':'Contraseña de MQTT',
		'system_I_XVII':'Tema en el que se enviarán las alarmas(opcional)',
		'system_I_XVIII':'Latitud del concentrador (opcional)',
		'system_I_XIX':'Longitud del concentrador (opcional)',
		'system_I_XX':'Resultado de una transacción exitosa',
		'system_I_XXI':'O',
		'system_I_XXII':'Resultado de una transacción fallida',
		'system_I_XXIII':'Código de error para detectar el problema',
		'system_I_XXIV':'Nota: CODE_ERROR (LISTA PENDIENTE)',
		//history_meter/id_meter/starDate/endDate
		'HM_IM_SD_ED_I':'Nota: El registro del perfil de carga se muestra por día y cada 15 minutos',
		'HM_IM_SD_ED_II':'CARGAR PERFIL',
		'HM_IM_SD_ED_III':'Array con perfiles de carga diarios',
		'HM_IM_SD_ED_IV':'Fecha',
		'HM_IM_SD_ED_V':'Día del perfil',
		'HM_IM_SD_ED_VI':'Hora',
		'HM_IM_SD_ED_VII':'Hora',
		'HM_IM_SD_ED_VIII':'Tipo',
		'HM_IM_SD_ED_IX':'Canal',
		'HM_IM_SD_ED_X':'Canal de comunicación',
		'HM_IM_SD_ED_XI':'Valores',
		'HM_IM_SD_ED_XII':'Alertas',
		'HM_IM_SD_ED_XIII':'Lista de eventos ocurridos en las fechas seleccionadas',
		'HM_IM_SD_ED_XIV':'Nota: El canal de comunicación recibe los siguientes parámetros:',
		'HM_IM_SD_ED_XV':'Energía entregada (kWh)',
		'HM_IM_SD_ED_XVI':'Energia recivida (kWh)',
		'HM_IM_SD_ED_XVII':'Cuadrante I (kVAR)',
		'HM_IM_SD_ED_XVIII':'Cuadrante II (kVAR)',
		'HM_IM_SD_ED_XIX':'Cuadrante III (kVAR)',
		'HM_IM_SD_ED_XX':'Cuadrante IV (kVAR)',
		'HM_IM_SD_ED_XXI':'Demanda Entregada(kW)',
		'HM_IM_SD_ED_XXII':'Demanda Recivida (kW)',
		//history_meter/id_meter/starDate/endDate/tipe
		'HM_IM_SD_ED_T_I':'Nota: Si el tipo de canal no se especifica en la URL de los datos del canal de solicitud, se muestra el valor predeterminado.',
		'HM_IM_SD_ED_T_II':'Nota: Si el resultado es negativo ("value": - 1) significa que no hay perfil.',
		///instant_record/meder_id/starDate/endDate
		'IR_MI_SD_ED_I':'Nota: Guarda instantánea cada 15 minutos',
		'IR_MI_SD_ED_II':'Hora del instante',
		'IR_MI_SD_ED_III':'Corriente',
		'IR_MI_SD_ED_IV':'Voltaje',
		'IR_MI_SD_ED_V':'Poder activo',
		'IR_MI_SD_ED_VI':'Poder activo',
		'IR_MI_SD_ED_VII':'Poder aparente',
		'IR_MI_SD_ED_VIII':'Poder reactivo',
		'IR_MI_SD_ED_IX':'Frecuencia de poder',
		'IR_MI_SD_ED_X':'Total KWH entregado',
		'IR_MI_SD_ED_XI':'Total kWH recibido',
		'IR_MI_SD_ED_XII':'Consumo total',
		'IR_MI_SD_ED_XIII':'KVAR I TOTAL',
		'IR_MI_SD_ED_XIV':'KVAR II TOTAL',
		'IR_MI_SD_ED_XV':'Demanda anterior entregada',
		'IR_MI_SD_ED_XVI':'Demanda anterior recibida',
		//statistics
		'statistics_I':'Paquete entregado',
		'statistics_II':'Paquete recibido',
		'statistics_III':'Paquete perdido',
		'statistics_IV':'Medidor en linea',
		'statistics_V':'Medidor en linea',
		'statistics_VI':'Tiempo de votación',
		'statistics_VII':'Timestamp de alerta con formato MySQL',
		'statistics_VIII':'Calidad de servicio',
		'statistics_IX':'Pérdida de paquetes por medidor',
		//meters/reading
		'M_READING_I':'Total KWH entregado al cliente',
		'M_READING_II':'Total CFE KWh entregado por el cliente',
		'M_READING_III':'Total de saldo KWH entregado y recibido',
		'M_READING_IV':'Total KVArh del primer cuadrante',
		'M_READING_V':'Total KVArh del segundo cuadrante',
		'M_READING_VI':'Total KVArh del tercer cuadrante',
		'M_READING_VII':'Total KVArh del cuarto cuadrante',
		'M_READING_VIII':'Fecha y hora de los datos',
		'M_READING_IX':'Indica el estado del RELAY',
		'M_READING_X':'Número de seria del medidor inteligente',
		'M_READING_XI':'Ticket',
		//meter/sync
		'm_sync_I':'Estado del medidor',
		'm_sync_II':'Número de serie del medidor inteligente',
		'm_sync_IIV':'Ticket',
		'm_sync_IV':'Nota: Las acciones del estado del medidor son: Fuera de línea o falso',
		//Displays
		'displays':'DIRECCIÓN',
		//Displays
		'displays_I':'RESULTADO DE UNA TRANSACCIÓN EXITOSA',
		//displaysMeters
		'DMeters_I':'NÚMERO ÚNICO DE ASOCIACIÓN MEDORES INTELIGENTES DISPLAY',
		'DMeters_II':'DIRECCION DEL DISPLAY',
		'DMeters_III':'MAC DEL DISPLAY',
		'DMeters_IV':'NÚMERO DE SERIE DE MEDIDORES INTELIGENTES ASOCIADOS AL DISPLAY',
		//displaysMeters_I
		'DMetersI_I':'NOTA: La matriz de medidores debe especificar el número de serie único (longitud: 6) cada uno',
		//displays_B
		
		//meters/configuracion
		'M_C_I':'Dirección del medidor inteligente',
		'M_C_II':'Sistema de alarmas',
		'M_C_III':'Velocidad de transmisión',
		'M_C_IV':'Tipo de canal (energía suministrada)',
		'M_C_V':'Tipo de canal (energia recibida)',
		'M_C_VI':'Tipo de canal (demanda entregada)',
		'M_C_VII':'Fecha de construcción',
		'M_C_VIII':'Día del pago reducido',
		'M_C_IX':'Día de pago ',
		'M_C_X':'Trasnformar en decimales',
		'M_C_XI':'Durante el modo de prueba',
		'M_C_XII':'Tarifa de energía',
		'M_C_XIII':'Version del hardware',
		'M_C_XIV':'Estado del puerto de eventos',
		'M_C_XV':'Estado de la clave',
		'M_C_XVI':'Situación de la tarifa',
		'M_C_XVII':'Clave del medidor',
		'M_C_XVIII':'Quadrant',
		'M_C_XIX':'Tensión máxima',
		'M_C_XX':'Voltage mínimo',
		'M_C_XXI':'Interrupción mínima del disco',
		'M_C_XXII':'Salida minima para alarma',
		'M_C_XXIII':'Modelo del colector',
		'M_C_XXIV':'Modo de operación',
		'M_C_XXV':'Pulsos KH',
		'M_C_XXVI':'Número de serie del medidor inteligente',
		'M_C_XXVII':'Version del software',
		'M_C_XXVIII':'Plantilla de configuraciones',
		'M_C_XXIX':'Zona horaria',
		'M_C_XXX':'Tiempo de espera de LCD',
		'M_C_XXXI':'Zona horaria',
		'M_C_XXXII':'Vendedor',
		//meters_config_I
		'm_config_I':'NOTA: El archivo de configuración es una plantilla (.json) exportada directamente desde el programa Soft Terminal, seleccionando la opción de configuración de plantillas de configuración en el menú de programación de parámetros.',
		'm_config_II':'Respuesta de JSON con Array con un objeto para cada medidor:',
		'm_config_III':'UID DE NUEVO MEDIDOR INTELIGENTE',
		'm_config_IV':'TICKET DE TRANSACCION',



			//COMMANDS_
			'TYP_COM_C':'Tipo de comando',
			'op_mod_ty_c':'Tipo de modo de operacion',
			'reg_mode_c':'Flujo del medidor inteligente',
		//METERS_SN_OPERATIONMODE
			'msnop':'Modo de operación',
			'msnrm':'Modo de registro'


		//unsolicited_request.html *ESPAÑOL*
		'TITILE_UNSOLICITED' : 'Solicitudes no requeridas',
		'PARAPHUNSOL_ONE' : 'Este comportamiento se utiliza para enviar alertas o circunstancias excepcionales como un mecanismo que utiliza el protocolo MQTT con calidad QoS2\u002C	 que es la forma más segura. Del mismo modo\U201A cada mensaje se cifra con AES 128 y con un formato JSON.',
		'PARAPHUNSOL_TWO' : 'Antes de cualquier transacción con MQTT\u002C debe establecer la dirección IP del servidor MQTT\u002C el usuario\u002C la contraseña y el tema. (Ver más detalles)',
		'PARAPHUNSOL_TRE' : 'The payload structure sent is the following:',
		'SUBTITLEUNS_TWO' : 'Alertas MQTT',
		'ONEFIELD_UNSOLI' : 'Marca de tiempo del instante',
		'TWOFIELD_UNSOLI' : 'Consumo del medidor',
		'TREFIELD_UNSOLI' : 'Código IUD para identificar la alarma',
		'FOUFIELD_UNSOLI' : 'Serial del medidor',
		'SUBTITLEUNS_TRE' : 'MENSAJE DE PERFILES FINAL',
		'PARAPHUNSOL_FOU' : 'Después de cada mensaje\u002C la API esperará una confirmación para cada mensaje enviado. La confirmación debe ser cifrada y en formato JSON.',
		'PARAPHUNSOL_FIV' : 'La estructura de carga útil recibida es la siguiente:',
		'FIVFIELD_UNSOLI' : 'Todos los perfiles ya están listos',
		'SIXFIELD_UNSOLI' : 'Mensaje recibido correctamente', 
		'SEVFIELD_UNSOLI' : 'Error al recibir mensaje'

		

	});
	$translateProvider.preferredLanguage('es');
	$translateProvider.useSanitizeValueStrategy('escape');
	$locationProvider.hashPrefix('');

	
	
});
